### ISSUE TITLE
create cortex config info for creation of forms automatically when props of a type occur

### ISSUE THREAD

**Issue by invisig0th** [vertexproject/synapse#100]
when form X has an fqdn prop, the cortex should be able to be configured to create inet:fqdn tufo as well as a result of encountering that value

**Comment by williballenthin** [comment]
in my project, i call a routine that pulls apart a tufo into other, smaller tufos a "dissector" (no relation to vivisect/dissect :-) ). i have a couple of classes of dissectors, which im happy to share, but the most relevant to this issue is the "type dissector". 

in my project, i am careful to ensure that each type is used as the ptype for exactly one form. this means i can use instances of a type as references to an associated form instance. that is, given form `X` with prop `fqdn` with `ptype=inet:fqdn`, the value of `X:fqdn` is the primary prop of an `inet:fqdn` form.

with this knowledge, the loader in my project automatically generates and installs `on:tufo:add` handlers that dissect any tufo that has props that point to another tufo. this ensures that the pointed-to tufo always exists. this is easy with the cortex datamodel introspection APIs.

here is an implementation of this idea: https://gist.github.com/williballenthin/f6e41282ca15ca9e6fed79206a6bbff4

you are welcomed to incorporate this idea into cortex, or ignore it. this behavior snaps in nicely without being a part of the cortex core.

**Comment by vertexmc** [comment]
This is OBE by autoadds / on node:add / prop:set / etc
