### ISSUE TITLE
"File" data model (files.py) needs file:hasname (or file:hasbase).

### ISSUE THREAD

**Issue by therealsilence** [vertexproject/synapse#375]
A given file (set of bytes) may have any number of arbitrary names. Currently, file:bytes nodes include a secondary :name property. However, file-to-filename is a one-to-many relationship, so this secondary property is only useful for convenience (e.g., display purposes such as show:cols()).

The model needs a node that can show the relationship(s) between a file (file:bytes) and an arbitrary filename (file:base). Recommendations:
- comp node where

  - primary property is the combination if the file (file:bytes GUID) and the filename (file:base, not file:path; a path implies a file system which implies a host (it:hostfile), we're just talking about base names here).
  - No additional secondary properties (besides file:hasname:file and fille:hasname:name) needed.

Note that use of the file:bytes GUID in this (or any) node has analytical implications depending on how the file:bytes node is formed (e.g., from known bytes / complete superhash GUID or from a single hash / no bytes).

**Comment by e2-ibm** [comment]
+1

Agree this is a need -- having an ability to store many filenames per file will be helpful for modeling things like

- multiple ITW filenames from VT
- filenames gathered from other OSINT sources where a full file path is not provided
- etc.

And allow us to pivot and find what files have been named certain things.

Prefer hasname over hasbase because it's more intuitive, even though the name property is file:base but don't have a strenuous preference.

Can think of no other secondary properties besides the ones already identified by @therealsilence

**Comment by invisig0th** [comment]
So would the expectation be that a file:hasbase ( or maybe file:haspath ) would be created from within the other node constructors such as it:hostfile ( representing it's presence in a filesystem ) or subfile ( representing it's (potentially named) presence within another file? )

**Comment by e2-ibm** [comment]
yeah i think that'd be good logic to have (it:hostfile and file:subfile causes another file:hasbase to be created)
