### ISSUE TITLE
"File" data model, file:subfile form has unnecessary secondary property :name

### ISSUE THREAD

**Issue by therealsilence** [vertexproject/synapse#376]
The file:subfile form has a secondary property :name that is unnecessary.

File:subfile represents a relationship consisting of a "parent" file and "child" file (or a "containing" file and a "contained" file). It is unclear what :name would represent with respect to the relationship between two files. In addition, each file that comprises the relationship already has its own (optional) :name property.

**Comment by e2-ibm** [comment]
No issues with this so long as https://github.com/vertexproject/synapse/issues/375 is implemented and we can store multiple filenames per file:bytes using a file:hasname node.

**Comment by invisig0th** [comment]
what about archive file cases where they archive file is able to specify a name for the contained file ( but we haven't seen it on a real filesystem) ?

**Comment by therealsilence** [comment]
Think it's still covered by the above - to create a file:subfile node (including "archive contains file") you need two file:bytes nodes. So even if we can't extract the archive (maybe it's password protected) or otherwise recover the bytes, we'd still need to "fabricate" a file:bytes node for the subfile, and that file:bytes node could have a (cosmetic) :name property, or could also be referenced in a file:hasname node (see #375).

So the only reason I can see to have a :name property on file:subfile would be for cosmetic purposes, similar to file:bytes. And begs the question of do we also need a (cosmetic) :name property for the "parent" file?

If we want to capture ostensible file names directly on a file:subfile node then I think we'd need to redo the form as a comp form where the name(s) of parent and child are optional.

**Comment by invisig0th** [comment]
I think it's slightly more than cosmetic since in many instances the name of the subfile ( but not the parent file name ) is directly specified within an archive file format ( ie some unknown zip contains woot.exe ).  while a subfile relationship may not always have a name, there are times when it does.

It kinda boils down to the whole "the name of a file is an aspect of it's relationship to a container" thing ( where in this case the container is a zip file rather than a filesystem )

**Comment by invisig0th** [comment]
Is the issue here mostly that we'd want to create singular way to ask about a file's observed names?  maybe we could have a file:filepath comp type that is also a form and is used as a secondary property on things like subfile and hostfile in order to create an additional node that represents that knowledge all folded together?
