### ISSUE TITLE
timehist with arbitrary units

### ISSUE THREAD

**Issue by invisig0th** [vertexproject/synapse#66]
nuf said

**Comment by MichaelSquires** [comment]
See chat conversation below for details about this ticket.

--------

visi [6:04 PM] 
hahah, totally.  lemme look it over quick and see if i can unpack my memory :smile:


[6:08] 
so, basically we need a couple things for that.  First and formost,  a function that can take a big list of (timestamp, thing) tuples and bucket them into a histogram based on arbitrary sized buckets.


[6:08] 
probably two different ways ( in linear time, and time cycles )

[6:08] 
so, for example

[6:08] 
linear hours vs hours of the day

[6:09] 
linear hours would make a potetially multi-day histogram with "hour" sized buckets


[6:10] 
but time cycles for "hours" would make a 24 hour histo bucketing them by "hour of the day" regardless of being days/weeks/etc apart.


[6:10] 
making any sense?


blackout [6:10 PM] 
yep

visi [6:11 PM] 
honestly, it's probably two functions

blackout [6:11 PM] 
what should the format of the histogram be? a list?

visi [6:11 PM] 
a list of:
    ( basetime, [things...]) 
tuples.


blackout [6:11 PM] 
rog


[6:11] 
timestamp is always an integer and always UTC?


visi [6:11 PM] 
so we can take len(things) and gen a chart or whatever, but also show the "things" in it if we want. :smile:


[6:12] 
times in synapse are all in millis since epoch :wink:


[6:12] 
( utc )


blackout [6:12 PM] 
check


visi [6:12 PM] 
( and can be negative )


[6:12] 
hehe, for things prior to 1970 :wink:


blackout [6:12 PM] 
things existed before 1970?


[6:12] 
crazy talk


visi [6:12 PM] 
so i've heard.  it's all hearsay :wink:


blackout [6:12 PM] 
lol


[6:13] 
i'll start working on those functions and ping you if i have questions


visi [6:13 PM] 
this will eventually then be called by storm query operators allowing analysts to dynamically generate histos of arbitrary nodes time info


[6:13] 
hawt


[6:13] 
feel free to begin synapse/lib/stat.py


[6:14] 
there are probably a bunch more that could be unified there ( some that probably already exist throughout the code, but we can hunt those down later )


blackout [6:15 PM] 
oh, i think i understand the use case: make a query and then plot them into a histogram so you can see that a lot of things all happened within a 24 hour period or always happen on a weekend


visi [6:15 PM] 
we may wanna talk about how to "name" the cyclic units.


[6:15] 
"days" would be linear, but "days/week" would be cyclci?


[6:15] 
exactly


[6:16] 
or happened most often in june of 2013 :wink:
